# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b130300d914343eca32df4976ab1f3f5d0710c5d3eaca399fd483d405af81177fc466effbbc4deb0b1b3cc65229dca4e3d7a06bdf79c6fd4f3933b76aa46dc0c

test:
  secret_key_base: fb09b48978d4213e8ac875e6dc2d4681fe977d4e5dde58460aa39eb2761ae647e0c23bbe6d50739fa2acfd3727ecb3271bc98b34db40ee936859d756b597ce42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
